### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by jupste** [Reksa97/tiralabra-synth#1]
Projekti ladattu koneelle 30.11. klo 15.05

Projektisi vaikuttaa oikein hienolta. Näin asiaan vihkiytymättömänä minun on vähän vaikea pysyä kärryillä ohjelman sisäisestä toiminnasta. Mutta sain ohjelman kyllä toimimaan ja pystyin sillä soittamaan muutamia epävireisiä sävelmiä. Ilmeisesti kuitenkaan kaikkia ylä- ja keskirivin näppäimiä ei ole kartoitettu sävelmiin esim. q ei tuota mitään ääntä. Tämä olisi ehkä hyvä tuoda ilmi itse ohjelmassa, esimerkiksi jos ohjelmassa olisi jokin "Help"-valikko.

###  Koodin laatu
Koodi vaikuttaa oikein toimivalta ja hyvin refaktoroidulta. Toiminnallisuudet ja käyttöliittymät on eroteltu selvästi eri paketeihin ja luokat on muodostettu järkevästi. Oikeastaan ainoa asia mikä kävi silmiin, on luokan ADSR suuri attribuuttimäärä. Voisiko näitä vähentää esimerkiksi antamalla luokalle double ja boolean tyyppiset taulukot, joiden kukin indeksi vastaa jotakin noista attribuuteista?

### Dokumentointi
Dokumentointi on pääosin hoidettu hyvin. Koodissa on vielä jonkin verran jäljellä kommentoitua koodia, eli nämä tiedot kannattaisi siirtää javadociin. Muuten dokumentointi vaikuttaa kattavalta. Tosiaan voisit ehkä dokumentoida ohjelman käyttöä tarkemmin mm. rivikomentojen suhteen. 

### Testaus 
Ohjelmassa on kattava testaus ainakin rivikattavuuden suhteen (>99%). Testit itsessään vaikuttavat testaavan järkeviä asioita. 

Kaiken kaikkiaan hyvin tehty ohjelmointityö, jonka taustalla on selvästi harrastuneisuutta tai muuta mielenkiintoa aihetta kohtaan.

**Comment by Reksa97** [comment]
Kiitos arvioinnista! Huomasinkin tämän vasta nyt... Käyttäjän opastamista täytyy tosiaan parantaa vielä. Attribuuttien järjestäminen on kyllä hyvä idea ja nykyinen systeemi on aika epämääräinen. Koitan lopulliseen palautukseen viilata nuo ja pistää kommentit kuriin.
